### PR TITLE
Create ShrimpCloud.md

### PR DESCRIPTION
**Pull request by zhangchaofei-java**
ShrimpCloud(虾云)

### CODE REVIEW

**Comment by zhangchaofei-java** [comment]
Yes, the above operations have been completed.

**Comment by dineshshenoy** [comment]
Can you provide the submission ID from this registration form (https://slingshot.filecoin.io/register-now/) so I can match up your application?

**Comment by zhangchaofei-java** [comment]
(Submission ID: 667931146)

**Comment by zhangchaofei-java** [comment]
@dineshshenoy Excuse me, the ID is already provided.

**Comment by zhangchaofei-java** [comment]
We have submitted the form, and here are the code and Id:

The verification code is:

barman-distort-speculate

(Submission ID: 667931146)

**Comment by dineshshenoy** [comment]
Considering this as a duplicate of #210 .  Please let me know if this should be considered as a separate entry.

**Pull request closed without merging**
