### PR TITLE
Add Datasets Request

### PR DESCRIPTION
**Pull request by gayeley**
more info :
Genome Aggregation Database  : https://github.com/awslabs/open-data-registry/blob/master/datasets/broad-gnomad.yaml
UK Biobank Pan-Ancestry Summary Statistics: https://github.com/awslabs/open-data-registry/blob/master/datasets/broad-pan-ukb.yaml
Genome in a Bottle : https://github.com/awslabs/open-data-registry/blob/master/datasets/giab.yaml

### CODE REVIEW

**Comment by pooja** [comment]
For each of the links in the table, please add both the links to the raw dataset and the GitHub/awslabs link that you linked here. Once you do that, we'll be happy to merge in the PR

**Comment by gayeley** [comment]
> For each of the links in the table, please add both the links to the raw dataset and the GitHub/awslabs link that you linked here. Once you do that, we'll be happy to merge in the PR

i had added both the links to the raw dataset  :  https://github.com/filecoin-project/slingshot/pull/406/files

**Review by gayeley — COMMENTED** [review]
more info :
Genome Aggregation Database : https://github.com/awslabs/open-data-registry/blob/master/datasets/broad-gnomad.yaml
UK Biobank Pan-Ancestry Summary Statistics: https://github.com/awslabs/open-data-registry/blob/master/datasets/broad-pan-ukb.yaml
Genome in a Bottle : https://github.com/awslabs/open-data-registry/blob/master/datasets/giab.yaml

**Comment by dineshshenoy** [comment]
Added via #411

**Pull request closed without merging**
