### PR TITLE
Starry sky in Yunnan

### PR DESCRIPTION
**Pull request by haiyaqingdao**

### CODE REVIEW

**Comment by dineshshenoy** [comment]
I couldn't locate your form entry (https://slingshot.filecoin.io/register-now).  Could you submit this form to complete the registration process?

**Comment by haiyaqingdao** [comment]
> 
> 
> I couldn't locate your form entry (https://slingshot.filecoin.io/register-now). Could you submit this form to complete the registration process?

Yes,Slack Handles: Patrick-li、grandhelmsman; Emails: desupport@grandhelmsman.com.

**Comment by liyunzhi-666** [comment]
I have submitted the project application and received the email. Why did the reviewer say that my registration information was not found?
image
do I need to register again?

**Comment by dineshshenoy** [comment]
Can you provide your submission ID and I can match this up with your registration form.

**Comment by haiyaqingdao** [comment]
> 
> 
> Can you provide your submission ID and I can match this up with your registration form.

Hello, the ID I submitted is: 667718849

**Review by dineshshenoy — APPROVED** [review]

**Pull request merged**
