### PR TITLE
YuncunHorizon

### PR DESCRIPTION
**Pull request by AlexY0905**
https://github.com/AlexY0905/slingshot-app   The design concept of our app is to design a suitable platform for users to search data, hoping to get official recognition.

### CODE REVIEW

**Comment by AlexY0905** [comment]
Through our app, it is convenient for you to retrieve valuable files of any type (such as pictures, videos, text files, etc.) and encourage you to upload your own valuable files.(PS: We will carry out background screening for illegal files and you may be in danger of being blocked)

**Comment by dineshshenoy** [comment]
Thanks for submitting an application.  Our team will validate for completeness and then assign reviewers from the competitions review panel.

**Comment by dineshshenoy** [comment]
The proposal looks ok, but you may be able to build bigger storage volumes by using one of the curated data sets.  It simplifies the problem without having to check for legality and also the volume can grow quickly.   Since prize volumes are linked to storage volumes, is there a reason why you prefer user uploaded data?

**Comment by AlexY0905** [comment]
> The proposal looks ok, but you may be able to build bigger storage volumes by using one of the curated data sets. It simplifies the problem without having to check for legality and also the volume can grow quickly. Since prize volumes are linked to storage volumes, is there a reason why you prefer user uploaded data?

Your data set is very good. It is rich and informative. However, I think Filecoin should be integrated with storage and retrieval. If customers can store their data and pay a certain cost, distributed storage will play its due value and attract more users. Filecoin can completely guarantee data security, we can use ipFS hot storage and Filecoin cold storage to protect the user's data, right?

**Comment by AlexY0905** [comment]
> The proposal looks ok, but you may be able to build bigger storage volumes by using one of the curated data sets. It simplifies the problem without having to check for legality and also the volume can grow quickly. Since prize volumes are linked to storage volumes, is there a reason why you prefer user uploaded data?

We've perfected our Slingshot, and we'd love to take part in this contest and store official data and all kinds of useful data

**Pull request merged**
