### PR TITLE
Xcloud

### PR DESCRIPTION
**Pull request by doodledz**
We've tried to registed our project. twice, in order to solve the following  question:

As of now，My project has used multiple Filecoin addresses. Could you please help us to consolidate these addresses on the leaderboard under one address？The project's addresses we'd like toconsolidate to slingshot are the followings:

t3uoxka76tfjg2q4vziknarnbvg5medytazxg75sjw76cuys4p2qo6ll4vjloynaoj3ombw462pxmu7lp7bgca
[The one we will use]

t3qabkpymgvmxscnek4m2bewunbemcesly7jgdzrdkmml2hiynk2bdx5eso2swz6ytz2ygxrfjjngvagshpp2q (which was submitted during the last registration in)

When  we  need to verify the Filecoin node, please let us use the correct one.

### CODE REVIEW

**Comment by dineshshenoy** [comment]
Can you resubmit this PR to have one application per project?  The current PR removes the template file and has two applications.   You can also fix address issues by emailing slingshot@filecoin.org

**Comment by doodledz** [comment]
> Can you resubmit this PR to have one application per project? The current PR removes the template file and has two applications. You can also fix address issues by emailing [slingshot@filecoin.org](mailto:slingshot@filecoin.org)

The other project was registered with a wrong wallet address. Would you pls just review the project as our final registration and ignore the other one?

**Comment by dineshshenoy** [comment]
I can't merge in this PR with two applications and removing the template file.  Which is the file you would like to keep?

**Comment by doodledz** [comment]
The application submitted by the email address qwcheung@gmail.com is the one we‘d like to keep. 

Would u pls ignore the earlier application submitted by the email address doodledz@gmail.com, which with the wrong wallet address.

**Comment by dineshshenoy** [comment]
There are two files in this PR.  XCloud.md and XCloudStore.md.  Can you specify which one should be reviewed?

**Comment by doodledz** [comment]
> There are two files in this PR. XCloud.md and XCloudStore.md. Can you specify which one should be reviewed?

Pls review XCloud.md as our final submit.

**Comment by koda9-inc** [comment]
@dineshshenoy  Hi Dinesh, any updates on the review?

**Comment by dineshshenoy** [comment]
Replacing with #340

**Pull request closed without merging**
