### PR TITLE
CloudEyes.md

### PR DESCRIPTION
**Pull request by Filecoin-ypool**

### CODE REVIEW

**Comment by Filecoin-ypool** [comment]
add UI

**Comment by dineshshenoy** [comment]
Thanks for submitting an application.  Our team will validate for completeness and then assign reviewers from the competitions review panel.

**Comment by Filecoin-ypool** [comment]
> Thanks for submitting an application. Our team will validate for completeness and then assign reviewers from the competitions review panel.

ok,thank you

**Comment by dineshshenoy** [comment]
This looks good.  Will the data be stored unencrypted or will it be encrypted?   If encrypted, we may need to do some verification steps during the competition -but it's permitted.

**Comment by dineshshenoy** [comment]
Congratulations. Your application has been approved and merged as an official participant for the Slingshot competition!
The following resources may be helpful as you begin:

[Competition Home](https://slingshot.filecoin.io/)
[Competition Rules](https://slingshot.filecoin.io/rules)
[FAQs](https://slingshot.filecoin.io/faq)
[Events calendar](https://slingshot.filecoin.io/events/) 
Office Hours
Master Classes
[Filecoin Docs] (https://docs.filecoin.io) 
[HackFS videos] (https://hack.ethglobal.co/showcase/myel-receOUiPSd63148qZ)
[Textile Powergate](https://docs.textile.io/powergate/)

Feel free to reach out in the slack community channels:
#fil-testnet-announce – For major announcements about the testnet and major software releases
#slingshot-announcements – For major announcements about the Slingshot program
#slingshot – For debugging help and community conversations throughout the course of the competition

**Pull request merged**
