### PR TITLE
sr2 json with miners

### PR DESCRIPTION
**Pull request by jsign**
Still WIP, since I'd like to make some tests.

But is based on the list of miners from the other folder. I think we should think about if makes sense to keep the other folder, or just this file as the source of truth.

cc @dineshshenoy  @ribasushi

### CODE REVIEW

**Comment by dineshshenoy** [comment]
In conversatoins with @ribasushi, we thought making them text and editable would be easier for miners to send PR's and edit the folder structure.   i don't have a strong opinion on which approach we choose.

If we do choose a json structure - let's name it so it's not powergate specific (non powergate users could leverage the same structure for their needs)

**Comment by jsign** [comment]
Yeah, I'd vote for JSON since the data in this file is more than miner addresses.
No problem in renaming to a more agnostic things.

One thing to be aware of that we can also discuss: should we point Powergates directly to the `master` version of this file?
We should be completely aware that any merged change will impact all hosted Powergates. (e.g: someone edits something and breaks format, etc).

Just raising awareness if that's OK. If we want a safer decision, we could have other options (e.g: point powergate to a daily updated file in another endpoint).

Thoughts?

**Comment by jsign** [comment]
I moved the json file to the `miners` folder.

We should be very careful that any edition of this file doesn't break being a JSON document.
For a bit we can use [this](https://jsonlint.com/) (just copy paste and validate), until we can also include some GH action to validate this file automatically.

Powergate will be ready very soon to use this file, so would be nice to decide and merge asap.

**Comment by dineshshenoy** [comment]
This works for me.   Since this is all in one file, let's change the path from miners/list.json to /miners.json   We don't have a need for a separate directory structure anymore

**Review by dineshshenoy — APPROVED** [review]
Approving - go ahead and merge after the path change please.

**Comment by jsign** [comment]
@dineshshenoy , done. I'll leave up to you if you want to delete the `miners` folder now.

**Pull request merged**
