### PR TITLE
request add financial market data into curated_dataset

### PR DESCRIPTION
**Pull request by ffteng47**

### CODE REVIEW

**Comment by ffteng47** [comment]
Historical tick prices and volumes of all ShangHai Futures Exchange instruments of China

**Comment by dineshshenoy** [comment]
Can you provide in the format of datasets.md ?

**Comment by ffteng47** [comment]
Hi,
So we provide a website which the data can be download also?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "filecoin-project/slingshot"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月18日(星期三) 上午6:41
收件人:&nbsp;"filecoin-project/slingshot"<slingshot@noreply.github.com&gt;;
抄送:&nbsp;"若水三千"<253528688@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [filecoin-project/slingshot] request add financial market data into curated_dataset (#366)





 
Can you provide in the format of datasets.md ?

**Comment by dineshshenoy** [comment]
Yes - the data needs to be publicly accessible and freely licensed.

**Comment by dineshshenoy** [comment]
Can you provide the source of this data and the license terms?  For curated datasets, we want to ensure that they are managed by a data provider

**Comment by ffteng47** [comment]
Sorry for so late to reply,we are preparing the request format&nbsp; listed in dataset.md.Now the website is ready ,we schedule to&nbsp; &nbsp;migrate data this weekend.There is no copyright for this dataset.
             Name   Descriptions   Size   Format   URL  
     Tick Prices   for Futures Market Dataset   Historical   tick prices and volumes of all China's commodity futures 
     and finacial futures.The size of dataset is still increasing about 1G   everyday now   300G   txt   http://106.14.247.61:40080/#/public  




Best,
Teng




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "filecoin-project/slingshot"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月21日(星期六) 上午6:23
收件人:&nbsp;"filecoin-project/slingshot"<slingshot@noreply.github.com&gt;;
抄送:&nbsp;"若水三千"<253528688@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [filecoin-project/slingshot] request add financial market data into curated_dataset (#366)





 
Can you provide the source of this data and the license terms?  For curated datasets, we want to ensure that they are managed by a data provider

**Comment by pooja** [comment]
Hey there, we'll be closing this PR, but if you'd like to request to add a new dataset, you can file an issue [here](https://github.com/filecoin-project/slingshot/issues/new?assignees=pooja&labels=dataset-request&template=dataset-request.md&title=%5Bdataset+request%5D+Enter+your+dataset+name+here)

**Pull request closed without merging**
