### PR TITLE
YuncunPlayer join slingshot

### PR DESCRIPTION
**Pull request by cchahahahahaha**
This is an automatic voice sharing platform for users to upload their own songs, bedtime stories and other sounds to the Filecoin network, which can only be viewed by authorized users.

### CODE REVIEW

**Comment by dineshshenoy** [comment]
Can you please resubmit this PR with a single file addition?  This PR removes some existing entries.

**Comment by cchahahahahaha** [comment]
we  delete some files and you can check again.

**Comment by cchahahahahaha** [comment]
> Can you please resubmit this PR with a single file addition? This PR removes some existing entries.

I don not known  what your meaning ， i  guess  i  need  to  delete  some  files。I  delete some files and you can check again。

**Comment by dineshshenoy** [comment]
This PR is currently deleting many files.  Can you instead create a new PR with a single file addition  (which I presume is uncunPlayer.md )

**Comment by dineshshenoy** [comment]
Resubmitted as #328

**Pull request closed without merging**
