### PR TITLE
docs: ipfscms.md new project request

### PR DESCRIPTION
**Pull request by ipfslab**
The IPFSCMS collaborative creation platform was born in May 2019. The main members have a senior blockchain background. We hope to create a collaborative creation and content management platform for the 5G era through the characteristics of blockchain distributed storage and data deposit.

### CODE REVIEW

**Comment by ipfslab** [comment]
The Vbank Platform, using ipfs storage, to build a time bank for medical care workers, medical social workers and medical volunteers, improve the performance indicator system of medical services, and form a new mode of integration of medical health and public welfare by matching service resources with big data of patients' needs.

## **Technical features：**
- **We Storage multiple type of data to prove the authenticity of an hour of volunteering**
    - [image] pictures of Service process.
    - [json] iBeacon positioning report data from iot.
    - [video] Monitor snapshot & records.
    - [audio] Wearable smart terminal records.
- **We provide a data browser to check for authenticity using hashes**
    - [person] Who did
    - [process] what did
    - [review] Who reviewed
- **We provide a Trading center using time currency**
    - one hour, which be proved, equals, one unit of time currency

**Comment by dineshshenoy** [comment]
I see two submissions.  If this is for two teams, can you resubmit as two different PR's?

**Comment by ipfslab** [comment]
> I see two submissions. If this is for two teams, can you resubmit as two different PR's?

resubmit with one mission, and another one in new PR.

**Comment by cwaring** [comment]
Closing this PR as it looks like the project was amended and merged in #53, feel free to re-open if this should also be considered.

**Pull request closed without merging**
